p8105_hw1_hz3023
================
2025-09-21

## Question 1

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   4.0.0     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.3     ✔ tidyr     1.3.1
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(moderndive)
data("early_january_weather")
Problem1 <- early_january_weather
variable.names(Problem1)
```

    ##  [1] "origin"     "year"       "month"      "day"        "hour"      
    ##  [6] "temp"       "dewp"       "humid"      "wind_dir"   "wind_speed"
    ## [11] "wind_gust"  "precip"     "pressure"   "visib"      "time_hour"

``` r
nrow(Problem1)
```

    ## [1] 358

``` r
ncol(Problem1)
```

    ## [1] 15

``` r
mean(Problem1$temp)
```

    ## [1] 39.58212

- There are 15 variables in this dataset. They are origin, year, month,
  day, hour, temp, dewp, humid, wind_dir, wind_speed, wind_gust, precip,
  pressure, visib, and time_hour. Using nrow, we can know that there are
  358 observations. Using ncol, we can know there are 15 variables. The
  mean temperature in this dataset is 39.58. \*\*\*

``` r
ggp_problem1= ggplot(Problem1, aes(x=time_hour, y=temp, color=humid))+geom_point()
ggsave("HW1P1ggp.pdf",ggp_problem1, width=8, height=6)
ggp_problem1
```

![](p8105_hw1_hz3023_files/figure-gfm/unnamed-chunk-1-1.png)<!-- -->

\*This scatter plot shows the variation of temperature throughout
January over time. The temperature fluctuates every day and there is no
discernible trend. However, the temperature is generally higher during
the day and lower at night. The period with higher humidity occurs more
frequently in the middle of January.

## Question 2

``` r
set.seed(1) 
RS<-rnorm(10)
LV<-RS> 0
CV<-letters[1:10]
FV<-factor(rep(c("low", "medium", "high"), length.out = 10))
Problem2<-data.frame(RS, LV, CV, FV)
mean(Problem2$RS)
```

    ## [1] 0.1322028

``` r
mean(Problem2$LV)
```

    ## [1] 0.6

``` r
mean(Problem2$CV)
```

    ## Warning in mean.default(Problem2$CV): argument is not numeric or logical:
    ## returning NA

    ## [1] NA

``` r
mean(Problem2$FV)
```

    ## Warning in mean.default(Problem2$FV): argument is not numeric or logical:
    ## returning NA

    ## [1] NA

- The mean for the random sample of size 10 from a standard normal
  distribution is 0.13. The mean for the logical vector is 0.6. Both
  character vector and factor vector don’t have mean.

``` r
as.numeric(Problem2$LV)  
```

    ##  [1] 0 1 0 1 1 0 1 1 1 0

``` r
as.numeric(Problem2$CV) 
```

    ## Warning: NAs introduced by coercion

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(Problem2$FV) 
```

    ##  [1] 2 3 1 2 3 1 2 3 1 2

- The code chunk converts FALSE into 0 and TRUE into 1 for the logical
  vector, which explains why we can calculate a mean for logical
  variables. For the character vector, the conversion produces NA values
  because characters cannot be directly coerced into numbers, so a mean
  cannot be calculated. For the factor vector, the conversion uses the
  underlying integer codes assigned to each level (e.g., “high” = 1,
  “low” = 2, “medium” = 3). However, taking the mean of these codes is
  not meaningful because the numeric values only represent labels, not
  quantities.
